// ====================================
// AVENLO CORE - PROJECT MODEL
// ====================================

import mongoose, { Document, Schema } from 'mongoose';

export type ProjectStatus = 
  | 'discovery'
  | 'scoping'
  | 'quoted'
  | 'accepted'
  | 'in-progress'
  | 'review'
  | 'completed'
  | 'paused'
  | 'cancelled';

export type ProjectPriority = 'low' | 'medium' | 'high' | 'critical';

export interface IProjectBrief {
  summary: string;
  requirements: string[];
  techStack: string[];
  deliverables: string[];
  complexityScore: number; // 1-10
  estimatedHours: number;
  estimatedBudget?: number;
  timeline?: string;
  notes?: string;
}

export interface IProject extends Document {
  // Basic Info
  name: string;
  slug: string;
  description: string;
  clientId: string; // Discord user ID
  clientName: string;
  
  // Status
  status: ProjectStatus;
  priority: ProjectPriority;
  progress: number; // 0-100
  
  // Brief (generated by AI)
  brief?: IProjectBrief;
  briefEncrypted?: string; // AES-256 encrypted brief
  
  // Discord Integration
  threadId?: string;
  dashboardMessageId?: string;
  channelId?: string;
  guildId: string;
  
  // Team
  leadDevId?: string;
  assignedDevs: string[];
  
  // Repository
  repository?: {
    url: string;
    name: string;
    owner: string;
    branch: string;
  };
  
  // Milestones
  milestones: Array<{
    id: string;
    title: string;
    description?: string;
    completed: boolean;
    completedAt?: Date;
  }>;
  
  // Financials
  quotedAmount?: number;
  paidAmount: number;
  currency: string;
  
  // Dates
  discoveryStartedAt?: Date;
  scopingCompletedAt?: Date;
  startedAt?: Date;
  completedAt?: Date;
  dueDate?: Date;
  
  // Metadata
  tags: string[];
  metadata: Map<string, unknown>;
  
  createdAt: Date;
  updatedAt: Date;
}

const ProjectBriefSchema = new Schema<IProjectBrief>(
  {
    summary: String,
    requirements: [String],
    techStack: [String],
    deliverables: [String],
    complexityScore: {
      type: Number,
      min: 1,
      max: 10,
    },
    estimatedHours: Number,
    estimatedBudget: Number,
    timeline: String,
    notes: String,
  },
  { _id: false }
);

const ProjectSchema = new Schema<IProject>(
  {
    name: {
      type: String,
      required: true,
    },
    slug: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
    },
    description: {
      type: String,
      default: '',
    },
    clientId: {
      type: String,
      required: true,
      index: true,
    },
    clientName: {
      type: String,
      required: true,
    },
    
    // Status
    status: {
      type: String,
      enum: ['discovery', 'scoping', 'quoted', 'accepted', 'in-progress', 'review', 'completed', 'paused', 'cancelled'],
      default: 'discovery',
      index: true,
    },
    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'critical'],
      default: 'medium',
    },
    progress: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },
    
    // Brief
    brief: ProjectBriefSchema,
    briefEncrypted: String,
    
    // Discord
    threadId: String,
    dashboardMessageId: String,
    channelId: String,
    guildId: {
      type: String,
      required: true,
      index: true,
    },
    
    // Team
    leadDevId: String,
    assignedDevs: [String],
    
    // Repository
    repository: {
      url: String,
      name: String,
      owner: String,
      branch: { type: String, default: 'main' },
    },
    
    // Milestones
    milestones: [{
      id: { type: String, required: true },
      title: { type: String, required: true },
      description: String,
      completed: { type: Boolean, default: false },
      completedAt: Date,
    }],
    
    // Financials
    quotedAmount: Number,
    paidAmount: {
      type: Number,
      default: 0,
    },
    currency: {
      type: String,
      default: 'USD',
    },
    
    // Dates
    discoveryStartedAt: Date,
    scopingCompletedAt: Date,
    startedAt: Date,
    completedAt: Date,
    dueDate: Date,
    
    // Metadata
    tags: [String],
    metadata: {
      type: Map,
      of: Schema.Types.Mixed,
      default: new Map(),
    },
  },
  {
    timestamps: true,
    collection: 'projects',
  }
);

// Indexes
ProjectSchema.index({ status: 1, guildId: 1 });
ProjectSchema.index({ clientId: 1, status: 1 });
ProjectSchema.index({ 'repository.owner': 1, 'repository.name': 1 });

// Pre-save hook to generate slug
ProjectSchema.pre('save', function (next) {
  if (this.isModified('name') && !this.slug) {
    this.slug = this.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
  }
  next();
});

export const Project = mongoose.model<IProject>('Project', ProjectSchema);
